services:
  - type: web
    name: specialwash-backend
    env: python
    region: ohio
    buildCommand: |
      npm install
      npm run build
      pip install -r requirements.txt
    startCommand: gunicorn wsgi:application --chdir ./src
    plan: free
    numInstances: 1
    envVars:
      - key: FLASK_APP
        value: src/app.py
      - key: FLASK_DEBUG
        value: 0
      - key: FLASK_APP_KEY
        value: "any key works"
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: BASENAME
        value: /
      - key: BACKEND_URL
        value: https://specialwash-backend.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: specialwash-db
          property: connectionString

databases:
  - name: specialwash-db
    region:
