"""empty message

Revision ID: 748fe00cb0e1
Revises: 952d200bec94
Create Date: 2025-07-17 19:27:51.009727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '748fe00cb0e1'
down_revision = '952d200bec94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_salida_producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fecha', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'usuario', ['usuario_id'], ['id'])
        batch_op.drop_column('fecha_salida')
        batch_op.drop_column('responsable')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_salida_producto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsable', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_salida', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fecha')
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
