"""empty message

Revision ID: eebb70fc4534
Revises: 3afbc81cea46
Create Date: 2025-07-10 19:26:15.002606

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eebb70fc4534'
down_revision = '3afbc81cea46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_entrada_producto', schema=None) as batch_op:
        batch_op.alter_column('precio_final_pagado',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_entrada_producto', schema=None) as batch_op:
        batch_op.alter_column('precio_final_pagado',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###
