"""empty message

Revision ID: ff965094d97b
Revises: 5e47bae69ebb
Create Date: 2025-07-10 07:32:43.437923

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ff965094d97b'
down_revision = '5e47bae69ebb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_entrada_producto', schema=None) as batch_op:
        batch_op.alter_column('numero_albaran',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('fecha_entrada',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('valor_iva',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.alter_column('precio_con_iva',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registro_entrada_producto', schema=None) as batch_op:
        batch_op.alter_column('precio_con_iva',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('valor_iva',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('fecha_entrada',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('numero_albaran',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
