from .base import db
from .user import User
from .producto import Producto
from .proveedor import Proveedor
from .entrada import Entrada
from .salida import Salida
from .maquinaria import Maquinaria
from .cliente import Cliente
from .coche import Coche
from .servicio import Servicio
